name: Playwright Pipeline
on:
  push:
    branches: [ main, tests ]
  pull_request:
    branches: [ main, tests ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Java 8
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-8-jdk
          echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> $GITHUB_ENV
          echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $GITHUB_ENV
      - name: Install all dependencies
        run: npm install
      - name: Run Playwright tests
        run: npx playwright test
  generate-allure-report:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Allure history
        if: always()
        continue-on-error: true
        run: git clone --branch gh-pages --single-branch --depth 1 https://github.com/${{ github.repository }} allure-history
      - name: Generate Allure Report
        run: allure generate allure-results -o allure-report --clean
  deploy-allure-report:
    runs-on: ubuntu-latest
    needs: generate-allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
